---
title: Gavin Eccles
timezone: GB
collections:
  drafts:
    title: Drafts
    output: true
    permalink: "/:categories/:title/"
  photography:
    title: Photography
    output: true
    permalink: "/:categories/:title/"
  posts:
    title: Posts
    output: true
  running:
    title: Running
    output: true
    permalink: "/:categories/:title/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: ''
    type: drafts
  values:
    layout: draft
    author_profile: true
    read_time: true
    sitemap: false
    noindex: true
- scope:
    path: ''
    type: photography
  values:
    layout: article
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: ''
    type: running
  values:
    layout: article
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
locale: en-US
title_separator: "-"
name: Gavin Eccles
description: Gavin Eccles, running fanatic, aspiring photographer, tech lover and
  a zest for life.
url: https://www.gavineccles.com
logo: "/assets/icons/v2/site-icon.png"
words_per_minute: 200
remote_theme: mmistakes/minimal-mistakes@4.19.1
repository: gavineccles17/personal_website
comments:
  provider: staticman_v2
staticman:
  branch: master
reCaptcha:
  siteKey: 6Lf5uugUAAAAAGcH-LCocNcoc_xRSqKeXFsZ6CWa
  secret: dhYNj9umBF+wnwX4qfG0wRJk6ILhSOnClU31x5hGVC48vhXWTlAWRNaTfgoqHBB+EpmGcyFWaBrcmIOQSWr+PRISW8D9lp5lc/4aVymLqDJpC+AYbwCEoaHroAt5kZRBM5NciRLmGiw+5gGMuf60AdEhrfsiNjCl67qgjOQwV0c=
breadcrumbs: true
search: true
search_provider: 
algolia:
  application_id: 
  index_name: 
  search_only_api_key: 
  powered_by: 
  files_to_exclude:
  - _pages/blog.markdown
  - _pages/home.markdown
  - _pages/photography.markdown
  - _pages/running.markdown
  - _pages/sitemap.markdown
  - _drafts/*.markdown
google_site_verification: d9S_Yrp70B0aU-9V2-qxvzXgxfu-qWUHS711hjzpsxY
bing_site_verification: 
analytics:
  provider: google-gtag
  google:
    tracking_id: G-ESYFBEXZ3M
twitter: 
facebook:
  username: gavin.eccles.5
  app_id: 
social:
  type: Person
  name: Gavin Eccles
  links:
  - https://facebook.com/gavin.eccles.5
  - https://ie.linkedin.com/in/gavin-eccles-8469a3150
  - https://instagram.com/gavineccles17
author:
  name: Gavin Eccles
  avatar: "/assets/images/selfie3.jpg"
  bio: Running fanatic and aspiring photographer with a zest for life.
  location: Ireland
  uri: https://www.gavineccles.com
  facebook: gavin.eccles.5
  github: gavineccles17
  google_plus: 
  medium: 
  instagram: gavineccles17
  twitter: 
  links:
  - label: Email
    icon: fas fa-fw fa-envelope-square
    url: mailto:gavineccles17@gmail.com
  - label: Strava
    icon: fab fa-strava
    url: https://www.strava.com/athletes/eccles_gavin
  - label: LinkedIn
    icon: fab fa-linkedin
    url: https://ie.linkedin.com/in/gavin-eccles-8469a3150
footer:
  links:
  - label: Strava
    icon: fab fa-strava
    url: https://www.strava.com/athletes/eccles_gavin
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/gavineccles17
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/gavineccles17
  - label: LinkedIn
    icon: fab fa-linkedin
    url: https://ie.linkedin.com/in/gavin-eccles-8469a3150
  - label: Email
    icon: fas fa-fw fa-envelope-square
    url: mailto:gavineccles17@gmail.com
include:
- _pages
- _redirects
exclude:
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Gemfile
- node_modules
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-algolia
- jemoji
- jekyll-include-cache
tag_archive:
  type: liquid
  path: "/tags/"
category_archive:
  type: jekyll-archives
  path: "/categories/"
compress_html:
  clippings: all
  ignore:
    envs: development
imagefolder: "/assets/images/"
