# Jekyll configuration

# Site settings
locale: "en-US"
title: "Gavin Eccles"
title_separator: "-"
name: "Gavin Eccles"
description: "Gavin Eccles, running fanatic, aspiring photographer, tech lover and a zest for life."
url: https://www.gavineccles.com
words_per_minute: 200
remote_theme: "mmistakes/minimal-mistakes@4.19.1"
# Comment hosting from Disqus
#comments:
#  provider: "disqus"
#  disqus:
#    shortname: "gavineccles"

# Comment hosting from Staticman
repository: "gavineccles17/personal_website"
comments:
  provider: #"staticman_v2"
staticman:
  branch: #"master"
reCaptcha:
  siteKey: #"6LfarVQUAAAAAOBAfH7NHqlBeI0sAx7jB7CcNp2u"
  secret: #"kJLDgpPcAPTcXPRne5EVo43urCYOrzrIx6GGoQnHKfTsSQ0l91oH6Bv1HqjJ+lmej1KfvbSIfDZ4T1NgOUYAJ6CBJtftmyQRuC7jYZtlXa+IADCc6NMIAkaiJIh9tlGdfVXpTXa92jfx5v2vUmJ5C35ZY8rhrY7OiJMDRlEzB5U="

# Site search from Algolia
search: true
search_provider: #"algolia"
algolia:
  application_id: #5XQCQN167D
  index_name: #ARAVIND_WEBSITE
  search_only_api_key: #5c1ac82194add16945031972f23d08f7
  powered_by: #"true"
  files_to_exclude:
    - _pages/blog.markdown
    - _pages/home.markdown
    - _pages/photography.markdown
    - _pages/running.markdown
    - _pages/sitemap.markdown
    - _drafts/*.markdown

# SEO and Analytics
google_site_verification : #"o5P1GShvyxwaztgNGI9OXDlnWXa9MjkhbyIPUNfNsFI"
bing_site_verification   : #"EB2419D7F9B094E998F87C560BAE12C8"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: #"UA-115949882-1"

# Social profile
twitter:
  #username: "aravindiyer"
facebook:
  username: "gavin_eccles"
  app_id: #"2013161692342257"
og_image: "/assets/images/self-sketch-splash.jpg"
social:
  type: "Person"
  name: "Aravind Iyer"
  links:
    #- "https://twitter.com/aravindiyer"
    - "https://facebook.com/gavin_eccles"
    #- "https://medium.com/@.aravindiyer"
    #- "https://www.linkedin.com/in/aravindiyer"
    - "https://instagram.com/gavineccles17"
    #- "https://plus.google.com/+AravindIyer"

# Site author
author:
  name: "Gavin Eccles"
  avatar: "/assets/images/selfie.jpg"
  bio: "Running fanatic and aspiring photographer with a zest for life."
  location: "Ireland"
  uri: "https://www.gavineccles.com"
  facebook: #"gavin_eccles"
  github: "gavineccles17"
  google_plus: #"+AravindIyer"
  medium: #".aravindiyer"
  instagram: gavineccles17
  twitter: #"aravindiyer"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:gavineccles17@gmail.com
    - label: "Strava"
      icon: "fab fa-strava"
      url: "https://www.strava.com/athletes/eccles_gavin"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://ie.linkedin.com/in/gavin-eccles-8469a3150"

# Site Footer
footer:
  links:
    - label: "Strava"
      icon: "fab fa-strava"
      url: "https://www.strava.com/athletes/eccles_gavin"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gavineccles17"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/gavineccles17"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://ie.linkedin.com/in/gavin-eccles-8469a3150"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:gavineccles17@gmail.com
      

# File reading
include:
  - _pages
  - _redirects
exclude:
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Gemfile
  - node_modules
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Jekyll processing
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Miscellaneous
permalink: /:categories/:title/
timezone: Asia/Kolkata # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-algolia
  - jemoji
  - jekyll-include-cache


# Collections - enable a collection for use as drafts
collections:
  drafts: 
    output: true
    permalink: /:categories/:title/
  photography:
    output: true
    permalink: /:categories/:title/
  running:
    output: true
    permalink: /:categories/:title/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Image assets folder
imagefolder: "/assets/images/"

# Build settings
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _drafts
  - scope:
      path: ""
      type: drafts
    values:
      layout: draft
      author_profile: true
      read_time: true
      sitemap: false
      noindex: true   #To hide from robots and crawlers
  # _photography
  - scope:
      path: ""
      type: photography
    values:
      layout: article
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _running
  - scope:
      path: ""
      type: running
    values:
      layout: article
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
